"""Telegram bot: long-polls getUpdates and handles subscription commands.

A bot can never message a user first — subscriptions work through the
t.me/<bot>?start=<code> deep link generated by the web UI. Pressing Start
delivers the code to us here, proving the user owns that Telegram account.
No webhook, no exposed port: fine for self-hosting.
"""

import asyncio
import logging

import httpx

from ..config import settings
from . import db

log = logging.getLogger(__name__)

_task: asyncio.Task | None = None
bot_username: str | None = None

HELP = (
    "I send alerts when a monitored expediente changes.\n\n"
    "/list — your active alert subscriptions\n"
    "/status — current status of your expedientes\n"
    "/stop <n> — stop one subscription (number from /list)\n"
    "/stopall — stop all your subscriptions\n\n"
    "To subscribe, use the activation link shown on the web page after "
    "adding a monitor."
)


def enabled() -> bool:
    return bool(settings.telegram_token)


def start() -> None:
    global _task
    if not enabled():
        log.info("TELEGRAM_TOKEN not set — bot disabled")
        return
    _task = asyncio.create_task(_run(), name="telegram-bot")


async def stop() -> None:
    if _task:
        _task.cancel()
        try:
            await _task
        except asyncio.CancelledError:
            pass


# ── Command handling (sync, DB-only — unit-testable) ─────────────

def handle_update(update: dict) -> str | None:
    """Returns the reply text for a message update, or None to stay silent."""
    msg = update.get("message") or {}
    text = (msg.get("text") or "").strip()
    chat_id = str((msg.get("chat") or {}).get("id", ""))
    if not text or not chat_id:
        return None
    chat_name = (msg.get("from") or {}).get("first_name", "")

    cmd, _, arg = text.partition(" ")
    cmd = cmd.split("@")[0].lower()  # tolerate /stop@BotName in groups
    arg = arg.strip()

    if cmd == "/start":
        return _cmd_start(chat_id, chat_name, arg)
    if cmd == "/list":
        return _cmd_list(chat_id)
    if cmd == "/status":
        return _cmd_status(chat_id)
    if cmd == "/stop":
        return _cmd_stop(chat_id, arg)
    if cmd == "/stopall":
        return _cmd_stopall(chat_id)
    return HELP


def _cmd_start(chat_id: str, chat_name: str, code: str) -> str:
    if not code:
        return "👋 Hello!\n\n" + HELP
    monitor, is_creator = db.claim_link_code(code)
    if monitor is None:
        return ("❌ This activation link is invalid or has expired.\n"
                "Generate a fresh one from the web page (Monitors → Telegram link).")
    cancel_code, created = db.add_subscription(monitor["id"], chat_id, chat_name)
    label = monitor["label"] or monitor["expediente_id"]
    if not created:
        return (f"ℹ️ You were already subscribed to <b>{label}</b>.\n"
                f"Your cancellation code is <code>{cancel_code}</code>.")
    state = monitor["last_state"] or {}
    estado = state.get("estado") or "(not checked yet)"
    reply = (
        f"✅ <b>Alerts activated</b> for <b>{label}</b>\n"
        f"Expediente: <code>{monitor['expediente_id']}</code>\n"
        f"Current Estado de Resolución: <code>{estado}</code>\n\n"
        f"You'll be alerted when the N.I.E., Estado or Fecha de Resolución "
        f"changes.\n"
        f"Cancellation code: <code>{cancel_code}</code> — use it on the web "
        f"page, or just send /stop here."
    )
    # The creator's claim also delivers the management link, so it's never
    # lost even if they didn't save it from the web page.
    if is_creator and settings.site_url:
        manage_url = f"{settings.site_url.rstrip('/')}/m/{monitor['manage_token']}"
        reply += (f"\n\n🔑 Management page (keep this private!):\n{manage_url}")
    return reply


def _cmd_status(chat_id: str) -> str:
    subs = db.subscriptions_for_chat(chat_id)
    if not subs:
        return "You have no active subscriptions."
    lines = []
    for sub in subs:
        state = sub["last_state"] or {}
        label = sub["label"] or sub["expediente_id"]
        lines.append(
            f"<b>{label}</b> — <code>{sub['expediente_id']}</code>\n"
            f"  Estado: {state.get('estado') or '(not checked yet)'}\n"
            f"  N.I.E: {state.get('nie') or '—'}\n"
            f"  Fecha de Resolución: {state.get('fecha_resolucion') or '—'}"
        )
    return "\n\n".join(lines)


def _cmd_list(chat_id: str) -> str:
    subs = db.subscriptions_for_chat(chat_id)
    if not subs:
        return "You have no active subscriptions."
    lines = ["Your subscriptions:"]
    for i, sub in enumerate(subs, 1):
        state = sub["last_state"] or {}
        estado = state.get("estado") or "(not checked yet)"
        label = sub["label"] or sub["expediente_id"]
        lines.append(f"{i}. <b>{label}</b> — <code>{sub['expediente_id']}</code>"
                     f" — {estado}")
    lines.append("\nSend /stop <n> to stop one of them.")
    return "\n".join(lines)


def _cmd_stop(chat_id: str, arg: str) -> str:
    subs = db.subscriptions_for_chat(chat_id)
    if not subs:
        return "You have no active subscriptions."
    if not arg and len(subs) == 1:
        target = subs[0]
    elif arg.isdigit() and 1 <= int(arg) <= len(subs):
        target = subs[int(arg) - 1]
    else:
        return "Which one? Send /list to see numbers, then /stop <n>."
    db.delete_subscription(target["id"])
    label = target["label"] or target["expediente_id"]
    return f"🔕 Alerts stopped for <b>{label}</b>."


def _cmd_stopall(chat_id: str) -> str:
    n = db.delete_subscriptions_for_chat(chat_id)
    return f"🔕 Stopped {n} subscription(s)." if n else "You have no active subscriptions."


# ── Long-polling loop ─────────────────────────────────────────────

async def _run() -> None:
    global bot_username
    api = f"https://api.telegram.org/bot{settings.telegram_token}"
    async with httpx.AsyncClient(timeout=65) as client:
        while bot_username is None:
            try:
                data = (await client.get(f"{api}/getMe")).json()
                if data.get("ok"):
                    bot_username = data["result"]["username"]
                else:
                    log.error("getMe failed (%s) — check TELEGRAM_TOKEN; retrying in 60s",
                              data.get("description"))
                    await asyncio.sleep(60)
            except asyncio.CancelledError:
                raise
            except Exception as e:
                log.warning("getMe network error (%s) — retrying in 10s", e)
                await asyncio.sleep(10)
        log.info("Telegram bot @%s polling for commands", bot_username)

        offset: int | None = None
        while True:
            try:
                params: dict = {"timeout": 50, "allowed_updates": '["message"]'}
                if offset is not None:
                    params["offset"] = offset
                data = (await client.get(f"{api}/getUpdates", params=params)).json()
                if not data.get("ok"):
                    log.error("getUpdates error: %s", data.get("description"))
                    await asyncio.sleep(5)
                    continue
                for update in data["result"]:
                    offset = update["update_id"] + 1
                    try:
                        reply = handle_update(update)
                    except Exception:
                        log.exception("Failed handling update %s", update.get("update_id"))
                        reply = "Something went wrong — please try again."
                    if reply:
                        chat_id = update["message"]["chat"]["id"]
                        await client.post(f"{api}/sendMessage", data={
                            "chat_id": chat_id, "text": reply, "parse_mode": "HTML",
                        })
            except asyncio.CancelledError:
                raise
            except Exception as e:
                log.warning("Bot polling error (%s) — retrying in 5s", e)
                await asyncio.sleep(5)


def deep_link(code: str) -> str | None:
    return f"https://t.me/{bot_username}?start={code}" if bot_username else None
